### ISSUE TITLE
flexibilitiy 4 installation problem

### ISSUE THREAD

**Issue by daviddz** [DESIGNfromWITHIN/Flexibility4Issues#11]
After I've installed the flexibility 4, only 'Home' default resources is created. The other default resources are not created.

**Comment by DESIGNfromWITHIN** [comment]
Hello David, this is correct and not a bug. 
Like a MODX install, I want Flexibility to be a clean starting point. 

I don't know what you are going to build so will not add resources... 

All the features and templates are ready to go, just create pages and select the correct template like: Homepage, Contact page or Gallery page. 

I might provide a extra package with a demo site later.

**Comment by daviddz** [comment]
Hi Menno, Thanks for clarifying that. I thought I didn't install it correctly. Can you direct me to the latest guide or tutorial on flexibility 4? I'm using the latest version (flexibility4-1.0.4-rc.transport).

**Comment by DESIGNfromWITHIN** [comment]
Did not have time for a new tut or video yet... 
Most info us here in the readme on gitHub and on http://flexibilitymodx.com 

Basically many settings are under System > Settings > (filter for flexibility4). 

These is a gallery now,  add under Components and create gallery page that use the gallery template. 

The homepage and basic pace have settings under Template Variables.

**Comment by daviddz** [comment]
Thanks, Menno for your help. I'll refer to the readme on gitHub.
