### ISSUE TITLE
Installation/removal problems

### ISSUE THREAD

**Issue by ghost** [DESIGNfromWITHIN/Flexibility4Issues#12]
Hung after clicking "continue" when trying to install, and overheated my laptop. It did install anyway, just the Console was hung and had to be closed manually. Couldn't uninstall it at all; from the console messages it was trying to uninstall all of my installed packages, such as MIGx and Wayfinder. It again overheated my laptop, but never did uninstall. It finally died after trying to remove the Gallery package. I can provide a text file taken from the console if you want; it's quite long. Site trashed; had to re-install Revo.

**Comment by DESIGNfromWITHIN** [comment]
Whow, that is BAD indeed, I have not seen this before... Could you send the error log?

**Comment by ghost** [comment]
I had installed it on an existing installation. I tried again on a new, empty installation, and was again not able to uninstall it.

Susan

**Comment by DESIGNfromWITHIN** [comment]
Thanks Susan, Did it work when you install it an a fresh version? Just the uninstall failed?

**Comment by ghost** [comment]
Yes. Even when installed on a fresh Revo it won't uninstall. And it's doing something extreme, because it gets the fan on my laptop running at full speed, while I can install all of the packages individually and it doesn't even get warm.

Susan

**Comment by DESIGNfromWITHIN** [comment]
Hey Susan, I just updated the Flexibility package to: 1.0.7-rc if you have time please try it.
It worked fine for me on MODX Cloud and on WAMP localhost.
- Clean install works
- Uninstall works (had to uninstall twice, first looked like it got stuck at uninstalling gallery, did refresh and the it worked)
- Re-install after uninstall worked, just had to manually install all sub-packes becouse they were already there
