### ISSUE TITLE
Contact template issues

### ISSUE THREAD

**Issue by acidic** [DESIGNfromWITHIN/Flexibility4Issues#13]
Fresh install.  modx 2.2.8  with current version of flexibility.  looks like chunk flex4_contact_form is missing.  i dont see it in my chunks but called by the contact template...    Don't remember if the contact page was to be created when installing flexibility4...

**Comment by acidic** [comment]
Also found if using the stock contact template  and a formit call.  nothing gets called. except for 

> div>
>     >div class="row">
>     >/div>
> /div>

something wrong with line 4 template Contact page  

[[$flex4_template_header]]
        >div>
            >div class="row">
                [[_flex4_sidebar_content:isnot=``:then=`
                >div class="small-8 columns">
                    [[_content]]
                    [[$Contact_Form]]
                >/div>
                >div class="small-4 columns">
                    [[_flex4_sidebar_content]]
                >/div>
                `:else=`
                >div class="small-12 columns">
                    [[_content]]
                    [[$Contact_Form]]
                >/div>
                `]]
            >/div>
        >/div>
[[$flex4_template_footer]]

did find that the TV flex4_sidebar_content was not assigned to this template.   though even assigning it, and putting in sidebar content.   same issue....      

i'm just going redo the template to what works for me as not sure were issue lies......  just so you know...   and others can find.. 

i have no idea how i closed this....     or how to post code correctly.....  :-(

**Comment by DESIGNfromWITHIN** [comment]
Many thanks for helping me acidic!

I will check the latest code I have. Should fix this in next update...

Btw to add code just add 4 spaces to you text:

```
this will be code
and more code on the next line becouse I add four spaces
```

This will be a normal line without spaces.

**Comment by DESIGNfromWITHIN** [comment]
This is fixed.
