### ISSUE TITLE
Contact Form Suggestion.

### ISSUE THREAD

**Issue by jxlusa** [DESIGNfromWITHIN/Flexibility4Issues#14]
Flex4 transport is great. Just tried Modx for the first time today. Setup was difficult because I did not read up on it but your transport package got me going pretty quick. One small suggestion: 
I changed [[++flex_contact_email]] to [[*flex_contact_email]] and added it as a TV assigned to the contact template. 
This way it will be easy to set individual emails to contact pages, and easy for clients to change where the contact form goes to. 
I found it difficult to find the proper site settings the first time, so I know clients will not be able to do it for the most part. A setting in the page Resources TV tab is easy to find and update.

**Comment by DESIGNfromWITHIN** [comment]
Hi, many thanks for the suggestion. I am planning to create better documentation (video's and docs) to showcase how to setup all settings.

I do like your point about making the email a TV, it would allow for multiple contact forms as well.

**Comment by jxlusa** [comment]
Cool. Yes, multiple contacts is part of what I had in mind. Thank you for making this template and package. It really did make it possible for me to start using Modx with a short learning curve.

**Comment by DESIGNfromWITHIN** [comment]
Many thanks jxlusa!
Great to hear that the package helped you.

This will be changed in the next update.
