### ISSUE TITLE
Contact form validation(No errors/Not send email)(ModX 2.2.9)

### ISSUE THREAD

**Issue by ghost** [DESIGNfromWITHIN/Flexibility4Issues#15]
Contact form don't send email, and also don't show validation errors.

**Comment by ghost** [comment]
Solution:
http://www.cmstricks.com/blog/2013/03/21/modx-form-submission-with-formit/

[[!+fi.validation_error_message]]
and
[[!+fi.successMessage]]
and
[[!+fi.error.name:notempty=`...

http://rtfm.modx.com/extras/revo/formit/FormIt.Validators
really bad documentation( Examples for old version(

**Comment by DESIGNfromWITHIN** [comment]
Many thanks!, Will be changed in the next version of Flexibility.
