### ISSUE TITLE
Gallery - In Album - No images

### ISSUE THREAD

**Issue by ghost** [DESIGNfromWITHIN/Flexibility4Issues#16]
maybe phpThumbsUp trouble or phpThumbsUp call trouble...
without phpThumbsUp all works well.

**Comment by DESIGNfromWITHIN** [comment]
Are you using WAMP or LAMP? or is the site online?

Anything in the error log?

**Comment by ghost** [comment]
WAMP(OpenServer)
http://newacropol.no-ip.org/
Error log is empty...

**Comment by DESIGNfromWITHIN** [comment]
Yes, WAMP.... I have had issues with phpThumbUp and Gallery on WAMP as well.
There are caching and url path issues on wamp unfortunately.

Please try online somewhere

**Comment by ghost** [comment]
Solution: 
http://forums.modx.com/thread/85893/new-version-of-phpthumbsup-supports-responsive-images#dis-post-474170

**Comment by ghost** [comment]
Okay... Found an another way to fix it, post in issues)
Why you're using TinyMCE instead of CKEditor?

Sorry for my eng..;

**Comment by DESIGNfromWITHIN** [comment]
I am used to TinyMCE and like that I can set preset CSS selectors. Will have a look at CKEditor, is it that much better?

**Comment by ghost** [comment]
Not much, BUT! it compatible with   http://modx.com/extras/package/ajaxmanager
Which is very good for me) you can try it yourself and if it will be fine - you can replace MCE with CKeditor)
