### ISSUE TITLE
Slider on Homepage

### ISSUE THREAD

**Issue by ghost** [DESIGNfromWITHIN/Flexibility4Issues#17]
Image slider items -> Add new element -> and only Title is availiable.

**Comment by ghost** [comment]
Solution: 
just copy MIGX TV options from pervious package in flex_orbit_items TV ))
please just return it in the next version of package)

---

Form Fields:
[{"caption":"Info", "fields": [{"field":"title","caption":"Slide title"},{"field":"description","caption":"Slide content (optional)","inputTVtype":"richtext"}]},{"caption":"Image", "fields":[{"field":"image_small","caption":"Slide image small (Smaller version of the image make it 480px wide)","inputTVtype":"image"},{"field":"image_medium","caption":"Slide image medium (Medium version of the image make it 738px wide)","inputTVtype":"image"},{"field":"image_large","caption":"Slide image large (Large version of the image make it 970px wide)","inputTVtype":"image"}]}]

---

Columns:
[{"header": "Slide content", "width": "160", "sortable": "true", "dataIndex": "title"},{"header": "Slide image", "width": "50", "sortable": "false", "dataIndex": "image_small","renderer": "this.renderImage"}]

**Comment by DESIGNfromWITHIN** [comment]
This is installed usually, I am guessing in WAMP something goes wrong with installing MIGX and then these settings are not set...

Please let me know if this also happend on a live install.
