### ISSUE TITLE
Orbit not showing images 

### ISSUE THREAD

**Issue by maherelaridi** [DESIGNfromWITHIN/Flexibility4Issues#19]
Hi Menno! 

Thank you for this extra. This is my second install and I love it. 

I have noticed that on both installs Orbit images' src shows as broken. PHPthunbsUp generates the automatic image url  like supposed to but nothing show.

I saw that 'leekohlbradley' had that problem on Modx forum but I didn't any suggested solution. I tried to re-install phpthumbsup. nothing worked.

Note: 

Fresh MODX Revolution 2.2.10-pl (traditional) Install 
Fresh Flexibility 4 1.1.1

Thanks!

**Comment by maherelaridi** [comment]
I got it to work. 

Thanks for @jellefaber for finding that out. 

http://forums.modx.com/thread/85893/new-version-of-phpthumbsup-supports-responsive-images.

**Comment by shopcoop** [comment]
http://forums.modx.com/thread/85893/new-version-of-phpthumbsup-supports-responsive-images?page=2#dis-post-483213

Tried the above... doesnt seem to like me :(
