### ISSUE TITLE
Articles does not install

### ISSUE THREAD

**Issue by frogabog** [DESIGNfromWITHIN/Flexibility4Issues#3]
Articles doesn't seem to be shown in Package Management, nor does it install.  Tried two ways, first with other packages installed, and second as a fresh first package.

**Comment by DESIGNfromWITHIN** [comment]
Does Articles install if you try manually? 

Does it say anything in the error log? 

Where did you install? (local host, own hosting or MODX Cloud)

**Comment by frogabog** [comment]
It does install manually just fine. I installed flexibility4 on cloud both times. Once after installing other extras first, once as fresh. 
Am sending error log from the fresh install separately.

Menno Pietersen notifications@github.com wrote:

> Does Articles install if you try manually? 
> 
> Does it say anything in the error log? 
> 
> Where did you install? (local host, own hosting or MODX Cloud) 
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/DESIGNfromWITHIN/Flexibility4Issues/issues/3#issuecomment-18468851

## 

Sent from my Android phone with K-9 Mail. Please excuse my brevity.

**Comment by DESIGNfromWITHIN** [comment]
This should be fixed with version 1.0.2-rc
