### ISSUE TITLE
Front End Gallery does not show images due to bad URL

### ISSUE THREAD

**Issue by thijsvandamme** [DESIGNfromWITHIN/Flexibility4Issues#4]
After a fresh install on localhost of both modx-2.2.7-pl and flexibility-4, I created a gallery, uploaded a ZIP. Then created a page and assigned the flex-4-gallery template. The images do not show. 
The URL behind the images is: 
phpthumbsup/w/235/h/235/zc/1/src//CMS/modx/assets/gallery/1/1.jpg

**Comment by acidic** [comment]
Same issue  url for me phpthumbsup/w/980/zc/1/src//assets/gallery/1/1.jpg

**Comment by DESIGNfromWITHIN** [comment]
This should be fixed
