### ISSUE TITLE
Fatal Error when opening googlesitemap page for editing.

### ISSUE THREAD

**Issue by thijsvandamme** [DESIGNfromWITHIN/Flexibility4Issues#5]
I get the following error when opening googlesitemap page in the manager

Fatal error: Call to a member function get() on a non-object in C:\xampp\htdocs\www\CMS\modx\core\cache\includes\elements\modplugin\12.include.cache.php on line 116

**Comment by acidic** [comment]
Same issue in trying to edit in manager.    going to http://sitename.com/sitemap    get a 500 Error Site temporarily unavailable.

**Comment by allanjpb** [comment]
Same issue both on Localhost and modx cloud
localhost ubuntu 12.04
Modx 2.2.8

**Comment by DESIGNfromWITHIN** [comment]
I will recreate the site map at a later time.
