### ISSUE TITLE
Notice of MIGX when opening Home

### ISSUE THREAD

**Issue by thijsvandamme** [DESIGNfromWITHIN/Flexibility4Issues#6]
I get the following warning when opening the home page:

Notice: Undefined index: configs in C:\xampp\htdocs\www\CMS\modx\core\components\migx\model\migx\migx.class.php on line 884

(localhost, modx-2.2.7-pl, fresh install)

Then when I try to add Image to the slider i get the following:

Notice: Undefined variable: packageName in C:\xampp\htdocs\www\CMS\modx\core\components\migx\model\migx\migx.class.php on line 299

Notice: Undefined index: formcaption in C:\xampp\htdocs\www\CMS\modx\core\components\migx\processors\mgr\fields.class.php on line 138

Notice: Undefined variable: counts in C:\xampp\htdocs\www\CMS\modx\core\components\migx\model\migx\migx.class.php on line 942

I can however add images to the slider. And they are displayed correctly on the homepage :)
Some more machine information:
Apache/2.4.3 (Win32) OpenSSL/1.0.1c PHP/5.4.7

**Comment by DESIGNfromWITHIN** [comment]
Thanks for the feedback, I am working on a update that should fix a lot of issues... Hope to finish in 1-2 weeks.

**Comment by thijsvandamme** [comment]
Hey Menno,

Laat me weten als ik voor je kan testen...

Mvg,

Thijs

  _Thijs Van Damme_
3801 Georgia Ave NW #504
20011 Washington DC
United States
Tel: (+1) 202 722 0714
   http://www.linkedin.com/in/
 [image: Follow teststamp on Twitter] http://www.twitter.com/TvdWebDesign
[image: My QR VCard]
 Create your free signature:
http://r1.wisestamp.com/r/landing?promo=33&dest=http%3A%2F%2Fwww.wisestamp.com%2Femail-install%3Futm_source%3Dextension%26utm_medium%3Demail%26utm_campaign%3Dpromo_33
CLICK
HERE!http://r1.wisestamp.com/r/landing?promo=33&dest=http%3A%2F%2Fwww.wisestamp.com%2Femail-install%3Futm_source%3Dextension%26utm_medium%3Demail%26utm_campaign%3Dpromo_33
​

2013/7/4 Menno Pietersen notifications@github.com

**Comment by DESIGNfromWITHIN** [comment]
This should be fixed with version 1.0.2-rc
