### ISSUE TITLE
unable to update flex-4-logo system setting

### ISSUE THREAD

**Issue by acidic** [DESIGNfromWITHIN/Flexibility4Issues#7]
Not sure why i cant update the flex-4-logo system setting   i can change everything else in the flexibility4 category.

**Comment by allanjpb** [comment]
Same issue.
Will rename png file

**Comment by DESIGNfromWITHIN** [comment]
Thanks for the feedback, I am working on a update that should fix a lot of issues... Hope to finish in 1-2 weeks.

**Comment by DESIGNfromWITHIN** [comment]
This should be fixed with version 1.0.2-rc

**Comment by acidic** [comment]
I found just deleting the setting.  then create a new setting with the same keyname, with the path to what i wanted worked as a fix.

**Comment by DESIGNfromWITHIN** [comment]
Thanks should be fixed in 1.0.4-rc
