### ISSUE TITLE
unable to install on modx 2.28

### ISSUE THREAD

**Issue by renevanp** [DESIGNfromWITHIN/Flexibility4Issues#8]
On 2.2.8 there is no "add new package"

There is "download extras" and then you can choose search locally
but Flexibilty can not be found

the zip file is placed in core/packages

**Comment by DESIGNfromWITHIN** [comment]
Thanks for the feedback, I am working on a update that should fix a lot of issues... Hope to finish in 1-2 weeks.

**Comment by DESIGNfromWITHIN** [comment]
This should be fixed with version 1.0.2-rc
