### ISSUE TITLE
colapsing of content boxes 

### ISSUE THREAD

**Issue by chj1955** [DESIGNfromWITHIN/Flexibility4Issues#9]
I have a form of colapsing of content boxes I have made a copy of your work and have a page with 2 boxes that i colapsing. 
See

http://www.forening.chj-it-konsulent.dk/index.php?id=20

**Comment by DESIGNfromWITHIN** [comment]
Hi thanks for your comment, could you explain your issue a bit more?

**Comment by chj1955** [comment]
I have try to show the problem in the attach document "word 2007"

Claus Jensen

Fra: Menno Pietersen [mailto:notifications@github.com] 
Sendt: 17. juli 2013 21:45
Til: DESIGNfromWITHIN/Flexibility4Issues
Cc: Claus
Emne: Re: [Flexibility4Issues] colapsing of content boxes (#9)

Hi thanks for your comment, could you explain your issue a bit more?

**Comment by DESIGNfromWITHIN** [comment]
I am sorry this is not working....
Please explain somewhere online or send me a email.
